/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.onelove.UI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author sudhi
 */
public class VapausAlertDialog extends javax.swing.JDialog implements ActionListener {

    public static final int NORMAL_TYPE = 0;
    public static final int ERROR_TYPE = 1;
    public static final int SUCCESS_TYPE = 2;
    public static final int WARNING_TYPE = 3;
    private onVapausAlertDialogListener mOKclickListener;
    private onVapausAlertDialogListener mCANCELclickListener;
    private onVapausAlertDialogListener mSUCCESSclickListner;
    private int userType = 0;

    /**
     * Creates new form SweetAlertDialog
     */
//    public VapausAlertDialog(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
//        initComponents();
//        this.setBackground(new Color(0, 0, 0, 0));
//    }
    public VapausAlertDialog() {

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        //To change body of generated methods, choose Tools | Templates.
    }

    public static interface onVapausAlertDialogListener {

        public void actionPerformed(VapausAlertDialog vapausAlertDialog);
    }

    public VapausAlertDialog(java.awt.Frame parent, int AlertType) {
        super(parent);
        initComponents();
        userType = AlertType;
        this.setBackground(new Color(0, 0, 0, 0));
        switch (AlertType) {
            case NORMAL_TYPE:
                btnSuccess.setIcon(new ImageIcon(getClass().getResource("/com/onelove/Image/okdefault.png")));
                btnSuccess.setRolloverIcon(new ImageIcon(getClass().getResource("/com/onelove/Image/okHover.png")));
                lblAvatar.setIcon(new ImageIcon(getClass().getResource("/com/onelove/Image/icons8-information-50.png")));
                btnCancel.hide();
                btnOK.hide();
                break;
            case ERROR_TYPE:
                btnSuccess.setIcon(new ImageIcon(getClass().getResource("/com/onelove/Image/cancelDefault.png")));
                btnSuccess.setRolloverIcon(new ImageIcon(getClass().getResource("/com/onelove/Image/cancelHover.png")));
                lblAvatar.setIcon(new ImageIcon(getClass().getResource("/com/onelove/Image/icons8-cancel-50.png")));
                btnSuccess.setText("OK");
                btnCancel.hide();
                btnOK.hide();
                break;
            case SUCCESS_TYPE:
                btnSuccess.show();
                btnOK.hide();
                btnCancel.hide();
                lblAvatar.setIcon(new ImageIcon(getClass().getResource("/com/onelove/Image/icons8-ok-50.png")));
                break;
            case WARNING_TYPE:
                btnSuccess.hide();
                lblAvatar.setIcon(new ImageIcon(getClass().getResource("/com/onelove/Image/icons8-error-50.png")));
                break;
        }
    }

    public VapausAlertDialog setTitleText(String title) {
        lbltitle.setText(title);
        return this;
    }

    public VapausAlertDialog setContentText(String content) {
        lblContent.setText("<html><head></head><body><p>"+content+"</p></body></html>");
        return this;
    }

    public VapausAlertDialog isDismiss() {
        this.dispose();
        return this;
    }

    public VapausAlertDialog setConfirmationText(String confirmationText) {
        if (userType == WARNING_TYPE) {
            btnOK.setText(confirmationText);
        } else {
            btnSuccess.setText(confirmationText);
        }
        return this;
    }

    public VapausAlertDialog setCancelText(String cancelText) {
        btnCancel.setText(cancelText);
        return this;
    }

    public VapausAlertDialog setOKText(String okText) {
        btnSuccess.setText(okText);
        return this;
    }

    public VapausAlertDialog setConfirmationClickLister(onVapausAlertDialogListener listener) {
        if (userType == WARNING_TYPE) {
            mOKclickListener = listener;
        } else {
            mSUCCESSclickListner = listener;
        }
        return this;
    }

    public VapausAlertDialog setCancelClickListener(onVapausAlertDialogListener listener) {
        mCANCELclickListener = listener;
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        lblContent = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnSuccess = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(464, 342));
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/onelove/Image/icons8-information-50.png"))); // NOI18N
        lblAvatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblAvatar);
        lblAvatar.setBounds(187, 23, 80, 80);

        lbltitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(0, 0, 0));
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Oops..!");
        lbltitle.setToolTipText("");
        lbltitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbltitle);
        lbltitle.setBounds(80, 110, 290, 20);

        lblContent.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblContent.setForeground(new java.awt.Color(0, 0, 0));
        lblContent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContent.setText("this is a test ");
        lblContent.setToolTipText("");
        lblContent.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblContent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblContent);
        lblContent.setBounds(70, 140, 320, 50);

        btnOK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/onelove/Image/okdefault.png"))); // NOI18N
        btnOK.setText("Ok");
        btnOK.setBorder(null);
        btnOK.setBorderPainted(false);
        btnOK.setContentAreaFilled(false);
        btnOK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOKMouseClicked(evt);
            }
        });
        getContentPane().add(btnOK);
        btnOK.setBounds(110, 200, 110, 50);

        btnSuccess.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuccess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/onelove/Image/successDefault.png"))); // NOI18N
        btnSuccess.setText("Ok");
        btnSuccess.setBorder(null);
        btnSuccess.setBorderPainted(false);
        btnSuccess.setContentAreaFilled(false);
        btnSuccess.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSuccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuccessMouseClicked(evt);
            }
        });
        getContentPane().add(btnSuccess);
        btnSuccess.setBounds(180, 200, 110, 50);

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/onelove/Image/cancelDefault.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(240, 200, 110, 50);

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/onelove/Image/backgroundBox.png"))); // NOI18N
        getContentPane().add(lblbackground);
        lblbackground.setBounds(0, 10, 454, 320);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
        // TODO add your handling code here:
        if (mOKclickListener != null) {
            mOKclickListener.actionPerformed(VapausAlertDialog.this);
        } else {
            isDismiss();
        }
    }//GEN-LAST:event_btnOKMouseClicked

    private void btnSuccessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuccessMouseClicked
        // TODO add your handling code here:
        if (mSUCCESSclickListner != null) {
            mSUCCESSclickListner.actionPerformed(VapausAlertDialog.this);
        } else {
            isDismiss();
        }
    }//GEN-LAST:event_btnSuccessMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        if (mCANCELclickListener != null) {
            mCANCELclickListener.actionPerformed(VapausAlertDialog.this);
        } else {
            isDismiss();
        }
    }//GEN-LAST:event_btnCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VapausAlertDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VapausAlertDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VapausAlertDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VapausAlertDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VapausAlertDialog dialog = new VapausAlertDialog(new javax.swing.JFrame(), 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSuccess;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lbltitle;
    // End of variables declaration//GEN-END:variables
}
